image: gradle:7.4-jdk11-alpine

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  # Remove caches
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - gradle assemble
  only:
    - dev
    - master

test:
  stage: test
  script:
    - export SPRING_PROFILES_ACTIVE=test
    - gradle check --stacktrace
    - gradle test --stacktrace
    - gradle jacocoTestReport
    - cat  build/reports/jacoco/test/html/index.html
  artifacts:
    paths:
      - build/reports/jacoco/*
    expire_in: 1 day
  only:
    - dev
    - master

deploy:
  stage: deploy
  only:
    - dev
  image: ruby:latest
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - heroku run --app $HEROKU_APP_NAME_STAGING migrate


